name: analysis
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - numba
  - pandas
  - pytables
  - scikit-learn
  - seaborn
  - statsmodels
  - jupyterlab
  - leidenalg
  - libpysal
  - lifelines
  - matplotlib
  - napari
  - nodejs
  - opencv
  - python-igraph
  - scanpy
  - scikit-image
  - shapely
  - tifffile
  - umap-learn
  - pillow
  - psutil
  - pysal
  - anndata
  - openpyxl
  - matplotlib-venn
