name: analysis
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel=6.28.0
  - numba=0.59.1
  - pandas=2.2.2
  - scikit-learn=1.4.2
  - seaborn=0.13.2
  - statsmodels=0.14.2
  - jupyterlab=4.2.3
  - lifelines=0.30.0
  - matplotlib=3.8.4
  - napari=0.4.19.post1
  - python-igraph=0.11.2
  - scanpy=1.10.1
  - scikit-image=0.24.0
  - shapely=2.0.4
  - tifffile=2023.8.12
  - umap-learn=0.5.5
  - pillow=10.3.0
  - psutil=5.9.0
  - anndata=0.10.8
  - openpyxl=3.1.2
  - matplotlib-venn=0.11.10
  - pyopengl=3.1.6
